### ISSUE TITLE
[consult] performance

### ISSUE THREAD

**Issue by Alice52** [huanzi-qch/springBoot#7]
Hi, @huanzi-qch 

  I have one question about `springboot-async` module, I know it implied by async for db operation. 
It will have high performance compared with sync opertaion. May I know this info?
   

Thanks.

**Comment by huanzi-qch** [comment]
我不太明白你的意思，异步多线程并行处理，当然要比同线程串行处理效率更高；可请前往官方文档查看springboot-async相关资料：https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/reference/htmlsingle/#boot-features-task-execution-scheduling

**Comment by huanzi-qch** [comment]
> Hi, @huanzi-qch
> 
> I have one question about `springboot-async` module, I know it implied by async for db operation.
> It will have high performance compared with sync opertaion. May I know this info?
> 
> Thanks.

我不太明白你的意思，异步多线程并行处理，当然要比同线程串行处理效率更高；可请前往官方文档查看springboot-async相关资料：https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/reference/htmlsingle/#boot-features-task-execution-scheduling

**Comment by watsondragon** [comment]
jackson在请求testByJson和testListByJson时，页面出现400错误，lz有发现吗？

**Comment by huanzi-qch** [comment]
> jackson在请求testByJson和testListByJson时，页面出现400错误，lz有发现吗？

不会吧？是不是你ajax请求的contentType没设置对
